# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
post_one = Post.create(title: "Vegan Williamsburg Neutra", body: "Keytar occupy wolf, banh mi before they sold out scenester hella Intelligentsia trust fund chia +1 3 wolf moon. McSweeney's tattooed kitsch pork belly cardigan. Aesthetic pug Odd Future next level bitters. Sriracha normcore whatever, Tumblr roof party four loko quinoa banh mi keytar chambray. Lo-fi meditation fanny pack next level. Intelligentsia flexitarian wayfarers taxidermy fashion axe, normcore before they sold out. Direct trade Neutra food truck Thundercats cray tousled.
Tote bag messenger bag Pitchfork four loko Intelligentsia, crucifix cornhole tilde dreamcatcher. Pop-up leggings kitsch, craft beer next level Thundercats fingerstache lumbersexual yr. Portland distillery wolf dreamcatcher. Pop-up squid taxidermy, occupy stumptown fixie beard banjo listicle ennui selvage. Bicycle rights Carles Austin, brunch letterpress wolf mixtape Kickstarter Schlitz blog yr lumbersexual. Small batch squid vegan pug wolf, freegan cliche. Street art tattooed semiotics, pickled chambray kogi next level pop-up disrupt swag keffiyeh.", image_url: "http://img.posterlounge.de/images/wbig/lucas-cranach-dae-herzog-heinrich-der-fromme-und-herzogin-katharina-von-mecklenburg-1302453.jpg")

post_two = Post.create(title: "Tote bag messenger bag " , body: "Literally fingerstache 90's retro meggings, put a bird on it gluten-free bitters selfies slow-carb twee irony master cleanse health goth. Sartorial authentic retro Wes Anderson Shoreditch. Retro pickled meggings, banh mi PBR&B 8-bit umami forage occupy direct trade normcore authentic four dollar toast narwhal jean shorts. Pour-over readymade next level, tofu sustainable small batch vinyl Godard forage Kickstarter four loko umami ugh selfies crucifix. Typewriter single-origin coffee locavore, listicle drinking vinegar vegan 90's Shoreditch food truck. Brunch kitsch deep v bespoke, meh small batch swag Odd Future heirloom selfies narwhal. Banksy flexitarian messenger bag, quinoa Odd Future church-key pop-up food truck vegan Etsy gastropub dreamcatcher cred.", image_url:"https://upload.wikimedia.org/wikipedia/commons/c/c3/Emile_Wauters_Madness_of_Hugo_van_der_Goes.jpg")

post_three = Post.create(title:"organic PBR&B", body:"Meditation Pitchfork selvage food truck, fashion axe slow-carb Wes Anderson pop-up Banksy forage chia Schlitz cronut chillwave. Forage cold-pressed street art sustainable drinking vinegar, mixtape sriracha Odd Future authentic trust fund American Apparel tilde selfies meh art party. Farm-to-table meditation Marfa keffiyeh chambray cronut, dreamcatcher wayfarers chillwave meh post-ironic kitsch small batch Helvetica. Tofu food truck Williamsburg Neutra shabby chic. Marfa pug ugh kitsch tofu readymade, gastropub street art 90's heirloom. Cred aesthetic church-key, Thundercats Portland squid kitsch tilde forage seitan cold-pressed VHS Tumblr Williamsburg. Sriracha freegan gastropub cliche, McSweeney's cray slow-carb Portland iPhone kitsch YOLO fanny pack.", image_url:"http://www.abroadintheyard.com/wp-content/uploads/The-Hunters-in-the-Snow-by-Pieter-Brueghel-the-Elder-1565.jpg")

post_four = Post.create(title:"Typewriter blog squid tofu", body:"Put a bird on it distillery deep v try-hard, fanny pack authentic Kickstarter swag hashtag cardigan mlkshk pug selfies scenester Odd Future. Typewriter pour-over mustache next level fingerstache slow-carb, paleo forage YOLO tote bag. Distillery disrupt art party, ennui Williamsburg PBR church-key McSweeney's letterpress pug raw denim. Biodiesel artisan art party 90's +1 Blue Bottle distillery. Raw denim dreamcatcher chambray, wayfarers Williamsburg Vice Shoreditch fingerstache photo booth pop-up you probably haven't heard of them. Swag whatever gluten-free farm-to-table paleo XOXO. Typewriter blog squid tofu.", image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Hans_Holbein_der_J%C3%BCngere_-_Der_Kaufmann_Georg_Gisze_-_Google_Art_Project.jpg/897px-Hans_Holbein_der_J%C3%BCngere_-_Der_Kaufmann_Georg_Gisze_-_Google_Art_Project.jpg")
